export { WeightAdaptation } from './adaptation/weight-adaptation';
export type { AdaptiveWeightKey } from './adaptation/weight-adaptation';
export { AssignmentLifecycle } from './assignment/assignment-lifecycle';
export type { CancellationResult } from './assignment/assignment-lifecycle';
export { GreedyAssignmentEngine } from './assignment/greedy-assignment.engine';
export type { AssignmentRunResult } from './assignment/greedy-assignment.engine';
export { EligibilityFilter } from './filters/eligibility.filter';
export { FeedbackUpdater } from './feedback/feedback-updater';
export { TopKRanker } from './ranking/top-k-ranker';
export type { RankedTutor } from './ranking/top-k-ranker';
export { AcademicScorer } from './scorers/academic.scorer';
export type { AcademicScore } from './scorers/academic.scorer';
export { CompositeScorer } from './scorers/composite.scorer';
export { FairnessScorer } from './scorers/fairness.scorer';
export { PreferenceScorer } from './scorers/preference.scorer';
export type { PreferenceScore } from './scorers/preference.scorer';
export { ScheduleScorer } from './scorers/schedule.scorer';
export { MaxHeap } from './utils/max-heap';
export type { HeapItem } from './utils/max-heap';
export { cosineSimilarity, dot, magnitude, oneHot } from './utils/vector-math';
